#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from __future__ import with_statement

import sys

sys.path.append (
	"third-party/gitdb")

sys.path.append (
	"third-party/gitpython")

sys.path.append (
	"third-party/pyyaml/lib")

sys.path.append (
	"third-party/smmap")

sys.path.append (
	"third-party/wbs-python")

import wbs.project

wbs.project.thirdparty.setup ()

# ex: noet ts=4 filetype=python
